# Generated by Django 5.0.6 on 2024-05-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_recipes_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='slug',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
    ]
