# Generated by Django 5.0.6 on 2024-05-20 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
